// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  serverUrl: '',
  production: true,
  version: env.npm_package_version,
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'es-EN'
  ]
};
